version: '3.8'

services:
  backend:
    build: ./ # Ruta al Dockerfile del backend
    container_name: backend_container
    ports:
      - "3001:3001"  # Puerto del contenedor:Puerto del host
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    networks:
      app-network:
        ipv4_address: 11.0.0.4

  mysql:
    container_name: MYSQL_DATABASE
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"  # Puerto del contenedor:Puerto del host
    volumes:
      - ~/contenedores/no_drive/db/mysql_data:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 11.0.0.3
  mongodb:
    image: mongodb-raspberrypi4-unofficial-r7.0.4:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ~/contenedores/no_drive/db/mongodb_data:/data/db
    networks:
      app-network:
        ipv4_address: 11.0.0.5

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/16
   



































































