version: '3'

services:
  backend:
    build: ./ # Ruta al Dockerfile del backend
    ports:
      - "3000:3000"  # Puerto del contenedor:Puerto del host
    depends_on:
      - mysql
      - mongo
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"  # Puerto del contenedor:Puerto del host
    volumes:
      - ~/contenedores/no_drive/db/mysql_data:/var/lib/mysql
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Puerto del contenedor:Puerto del host
    volumes:
      - ~/contenedores/no_drive/db/mongo_data:/data/db   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
   

   












